# this configMap contains the script to run in each k8s node
# the script will install required packages and download the driver at https://github.com/fstab/cifs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prepare-cifs-flecvolume-driver
  namespace: node-installer
data:
  install.sh: |
    #!/bin/bash
    # Update and install packages
    set -ex
    apt-get update -qy
    apt-get install cifs-utils jq util-linux coreutils -qy

    # parse VOLUME_PLUGIN_DIR per docs:
    # https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
    # https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#start-a-kubelet-process-configured-via-the-config-file

    KUBELET_VOLUME_PLUGIN_DIR=$(ps -efw | grep kubelet | egrep "\-\-volume-plugin-dir" | awk -F'volume-plugin-dir=' '{print $2}' | awk '{print $1}')
    KUBELET_CONFIG=$(ps -efw | grep kubelet | egrep "\-\-config=" | awk -F'--config=' '{print $2}' | awk '{print $1}')
    if [[ -n ${KUBELET_VOLUME_PLUGIN_DIR} ]]; then
      VOLUME_PLUGIN_DIR=${KUBELET_VOLUME_PLUGIN_DIR}
    elif [[ -n ${KUBELET_CONFIG} && -n $(grep -i volumePluginDir ${KUBELET_CONFIG}) ]]; then
      VOLUME_PLUGIN_DIR=$(grep -i volumePluginDir ${KUBELET_CONFIG} | awk '{print $2}')
    else
      VOLUME_PLUGIN_DIR="/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
    fi
    # VOLUME_PLUGIN_DIR="/usr/libexec/kubernetes/kubelet-plugins/volume/exec"
    
    mkdir -p "$VOLUME_PLUGIN_DIR/fstab~cifs"
    cd "$VOLUME_PLUGIN_DIR/fstab~cifs"
    curl -L -O https://raw.githubusercontent.com/fstab/cifs/master/cifs
    chmod 755 cifs
    ./cifs init
