apiVersion: v1
kind: Secret
metadata:
  name: cifs-secret
  namespace: default
type: fstab/cifs
data:
  username: 'bGFiLXRlc3Q=' # echo -n "lab-test" | base64
  password: 'blgkUlhLZ3ozSzNoJEJhN1lOUiNqVnQzIw==' # echo -n 'nX$RXKgz3K3h$Ba7YNR#jVt3#' | base64
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-cifs-mounted
  namespace: default
spec:
  containers:
  - name: ubuntu
    image: harbor.slot-59.pez.vmware.com/docker-hub-cache/library/ubuntu:latest
    command:
      - /bin/bash
    stdin: true
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: lab-cifs
      mountPath: /data/lab-cifs
  volumes:
  - name: lab-cifs
    flexVolume:
      driver: "fstab/cifs"
      fsType: "cifs"
      secretRef:
        name: "cifs-secret"
      options:
        networkPath: "//freenas.slot-59.pez.vmware.com/nfs/lab-test"
        mountOptions: "" #"dir_mode=0755,file_mode=0644,noperm"
